[package]
name = "golem-worker-executor-oss"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Golem worker executor service"

[lib]

# Rename to golem-worker-executor-oss ?
[[bin]]
name = "worker-executor-oss"
path = "src/server.rs"

[dependencies]
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-worker-executor-base = { path = "../golem-worker-executor-base", version = "0.0.0" }

anyhow = { workspace = true }
async-trait = { workspace = true }
cap-std = "2.0.0"
console-subscriber = { workspace = true }
figment = { workspace = true }
flume = "0.11.0"
humantime-serde = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.5.0"
tokio = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
wasmtime = { version = "=15.0.0", features = ["component-model"] }
wasmtime-runtime = { version = "=15.0.0" }
wasmtime-wasi = { version = "=15.0.0", features = ["preview2", "tokio"] }
wasmtime-wasi-http = { version = "=15.0.0" }
