[package]
name = "golem-common"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Shared code between Golem services"


[lib]


[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
dashmap = "5.5.0"
derive_more = "0.99.17"
fred = { workspace = true }
futures-core = { workspace = true }
humantime-serde = { workspace = true }
iso8601-timestamp = "0.2.11"
lazy_static = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
prometheus = { workspace = true }
prost = { workspace = true }
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
tonic-build = "0.9"
