name: CI
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: '0'
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Set version
        id: set-version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build docker images for all services and push to Docker Hub
        id: build-image
        run: |
          docker build -t golem-worker-executor:${{ env.VERSION }} -f golem-worker-executor-oss/docker/amd64/Dockerfile .
          docker build -t golem-server:${{ env.VERSION }} -f golem-cloud-server-oss/docker/amd64/Dockerfile .
          docker build -t golem-shard-manager:${{ env.VERSION }} -f golem-shard-manager/docker/amd64/Dockerfile .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-is

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Tests
        run: cargo test --all-features
  publish:
    needs: [build]
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-is

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          export VERSION="${{ steps.get_version.outputs.version-without-v }}"
          sed -i "s/0.0.0/$VERSION/g" golem-common/Cargo.toml
          sed -i "s/0.0.0/$VERSION/g" golem-worker-executor-base/Cargo.toml
          sed -i "s/0.0.0/$VERSION/g" golem-worker-executor-oss/Cargo.toml
          cargo publish -p golem-common --all-features --allow-dirty
          cargo publish -p golem-worker-executor-base --all-features --allow-dirty
          cargo publish -p golem-worker-executor-oss --all-features --allow-dirty
